### PR TITLE
genacls.sh needs to be run as root

### PR DESCRIPTION
**Pull request by pypingou**
We handle the permission at the sudo level but genacls.sh needs to be run as
root as it needs to be able to run chown and chroot commands.

### CODE REVIEW

**Comment by pypingou** [comment]
We will need a new release for pkgs01.stg sometime in the future

**Comment by ralphbean** [comment]
Can you link to the changes in ``genacls.sh`` so we can review what it's doing that needs root permissions?

**Comment by pypingou** [comment]
The genacls.sh can be found here: https://infrastructure.fedoraproject.org/infra/ansible/roles/distgit/files/genacls.sh

**Comment by ralphbean** [comment]
After discussing more in IRC, I'm :+1: on this.

**Comment by ralphbean** [comment]
So this will need a sudoers file change so that fedmsg-hub can sudo as root *only for the genacls script*.

**Comment by pypingou** [comment]
Thanks @ralphbean

**Pull request merged**
